create table if not exists public.playground_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.departments (
  department_id bigint generated by default as identity primary key,
  department_name text not null,
  department_code text unique,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.job_titles (
  job_title_id bigint generated by default as identity primary key,
  job_title_name text not null,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.employees (
  employee_id bigint generated by default as identity primary key,
  employee_code text unique not null,
  first_name text not null,
  last_name text not null,
  username text unique not null,
  email text unique not null,
  gender text,
  phone text,
  date_of_birth date,
  date_of_joining date,
  employment_status text,
  supervisor_id bigint references public.employees(employee_id) on delete set null,
  department_id bigint references public.departments(department_id),
  job_title_id bigint references public.job_titles(job_title_id),
  salary numeric(12,2),
  is_active boolean default true,
  is_manager boolean default false,
  is_remote_worker boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists public.employee_addresses (
  address_id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(employee_id) on delete cascade,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  country text,
  zipcode text,
  created_at timestamp with time zone default now()
);

create table if not exists public.employee_documents (
  document_id bigint generated by default as identity primary key,
  employee_id bigint references public.employees(employee_id) on delete cascade,
  document_name text,
  document_type text,
  file_path text,
  uploaded_at timestamp with time zone default now()
);

insert into public.departments (department_name, department_code)
values
  ('Engineering', 'ENG'),
  ('QA', 'QA'),
  ('HR', 'HR'),
  ('Finance', 'FIN')
on conflict (department_code) do nothing;

insert into public.job_titles (job_title_name, description)
values
  ('Test Engineer', 'Entry-level QA role'),
  ('Senior Test Engineer', 'Experienced QA professional'),
  ('Automation Architect', 'Automation strategy and framework design'),
  ('Software Developer', 'Application development'),
  ('HR Executive', 'People operations role')
on conflict do nothing;

alter table public.playground_items enable row level security;

create policy if not exists "Allow read access" on public.playground_items
  for select using (true);

create policy if not exists "Allow insert access" on public.playground_items
  for insert with check (true);

create policy if not exists "Allow update access" on public.playground_items
  for update using (true) with check (true);

create policy if not exists "Allow delete access" on public.playground_items
  for delete using (true);
