create table if not exists public.playground_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  created_at timestamp with time zone default now()
);

alter table public.playground_items enable row level security;

create policy if not exists "Allow read access" on public.playground_items
  for select using (true);

create policy if not exists "Allow insert access" on public.playground_items
  for insert with check (true);

create policy if not exists "Allow update access" on public.playground_items
  for update using (true) with check (true);

create policy if not exists "Allow delete access" on public.playground_items
  for delete using (true);
